language: go
sudo: required
go:
- "1.x"
before_script:
- go get github.com/googlecodelabs/tools/claat
script:
  - claat export cheatsheet.md
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
