language: node_js
sudo: required
before_install:
- curl -sSLO https://github.com/googlecodelabs/tools/releases/download/v2.2.0/claat-linux-amd64
- chmod +x claat-linux-amd64
script:
- ./claat-linux-amd64 export cheatsheet.md
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
